### ISSUE TITLE
spellwright npc wont spawn

### ISSUE THREAD

**Issue by Tweefhub** [Aurocosh/Spellwright#2]
dunno if I'm being stupid but I got 100 mana with empty NPC houses yet the spellwright NPC hasn't moved in.

**Comment by Aurocosh** [comment]
My bad, i wrote in description that you need 100 or more max mana in order to get Spellwright to spawn, the actual condition was more then 100. So 100 exactly will not work. I fixed this issue in version 0.8.1.3, Spellwright will now spawn if you have 100 mana exactly.

**Comment by Tweefhub** [comment]
thanks!
